archive_older_than_days: 30
# path to sqlite database
engine: "sqlite:///:memory:"
influx:
  dbname: pv-nodes
  host: localhost
  password: no-need
  port: 8086
  user: no-need
tags:
  host: testhost.de
  region: europe
read_interval_seconds: 10
min_uptime_seconds_before_reboot: 900
checks:
  internet_connection:
    interval_seconds: 900 # 15 minutes
    min_fails_in_row: 2
  port_found:
    interval_seconds: 600 # 10 minutes
    min_fails_in_row: 3

# specific for inverter type
inverter_type: "kaco"
kaco_port: "/dev/ttyUSB*"
kaco_inverter_ids: [1,2,3]

# specific for sma_rs485
sma_rs485_max_devices: 9
